name: palikorne
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  responsive_builder: ^0.4.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  auto_size_text: ^2.1.0
  webview_flutter: ^2.0.3
  flutter_material_color_picker: ^1.0.5
  flutter_colorpicker: any
  http: ^0.13.1
  share: ^2.0.1
  provider: ^5.0.0
  multiselect_formfield: ^0.1.2

flutter:
  assets:
    - lib/config/assets/logo.png
  uses-material-design: true
flutter_intl:
  enabled: true
